[package]
name = "rust-lox"
version = "0.1.0"
authors = ["Jason Fischer <jazzfisch@outlook.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"    # error handling
bytes = "1.3.0"      # helps manage buffers
thiserror = "1.0.38" # error handling

[dev-dependencies]
rstest = "0.21.0" # testing
